<?php
/* Template Name: Pickup location */
defined( 'ABSPATH' ) || exit;
get_header(); while ( have_posts() ) : the_post();
$key = (string) get_post_meta( get_the_ID(), '_rentacar_location_key', true ); $location = rentacar_venezia_v2_pickup_locations()[ $key ] ?? array(); $copy = rentacar_venezia_v2_landing_copy( $key ); $image = rentacar_venezia_v2_location_theme_image( $key );
?>
<main id="main-content" class="site-main landing-page"><article class="rc-container">
<?php get_template_part( 'template-parts/global/breadcrumbs' ); ?>
<header class="landing-hero landing-hero--location"><div><p class="eyebrow"><?php echo esc_html( $copy['eyebrow'] ); ?></p><h1><?php the_title(); ?></h1><p><?php echo esc_html( $copy['intro'] ); ?></p><a class="button" href="<?php echo esc_url( rentacar_venezia_v2_fleet_url_with_trip( array( 'pickup_location' => $location['value'] ?? '' ) ) ); ?>"><?php esc_html_e( 'Choose your car', 'rentacar-venezia-v2' ); ?></a></div><?php if ( has_post_thumbnail() ) { the_post_thumbnail( 'large', array( 'fetchpriority' => 'high', 'alt' => '' ) ); } elseif ( $image ) { ?><img src="<?php echo esc_url( $image['url'] ); ?>" width="<?php echo esc_attr( $image['width'] ); ?>" height="<?php echo esc_attr( $image['height'] ); ?>" alt="" fetchpriority="high"><?php } ?></header>
<ul class="landing-trust"><li><?php esc_html_e( 'Local service', 'rentacar-venezia-v2' ); ?></li><li><?php esc_html_e( 'Personal confirmation', 'rentacar-venezia-v2' ); ?></li><li><?php esc_html_e( 'A clear request process', 'rentacar-venezia-v2' ); ?></li></ul>
<?php if ( get_the_content() ) : ?><section class="landing-copy"><?php the_content(); ?></section><?php endif; ?>
<section class="landing-process"><p class="eyebrow"><?php esc_html_e( 'How pickup works', 'rentacar-venezia-v2' ); ?></p><h2><?php esc_html_e( 'A simple, personally confirmed process', 'rentacar-venezia-v2' ); ?></h2><ol><li><?php esc_html_e( 'Choose a car and send your travel details.', 'rentacar-venezia-v2' ); ?></li><li><?php esc_html_e( 'Our team confirms availability, price and pickup details.', 'rentacar-venezia-v2' ); ?></li><li><?php esc_html_e( 'Collect the vehicle using the confirmed arrangement.', 'rentacar-venezia-v2' ); ?></li><li><?php esc_html_e( 'Return details are agreed with the team.', 'rentacar-venezia-v2' ); ?></li></ol></section>
<?php $vehicles = class_exists( 'Rentacar_Core_Vehicle_Repository' ) ? array_slice( rentacar_venezia_v2_sort_fleet_vehicles( ( new Rentacar_Core_Vehicle_Repository() )->query() ), 0, 3 ) : array(); if ( $vehicles ) : ?><section class="landing-fleet"><h2><?php esc_html_e( 'Recommended cars', 'rentacar-venezia-v2' ); ?></h2><div class="vehicle-grid"><?php foreach ( $vehicles as $vehicle ) get_template_part( 'template-parts/vehicle/card', null, array( 'vehicle' => $vehicle, 'variant' => 'related' ) ); ?></div></section><?php endif; ?>
<?php rentacar_venezia_v2_render_landing_links( rentacar_venezia_v2_landing_related_locations( $key ), __( 'Related pickup locations', 'rentacar-venezia-v2' ) ); ?>
<section class="landing-cta"><h2><?php esc_html_e( 'Ready to plan your rental?', 'rentacar-venezia-v2' ); ?></h2><p><?php esc_html_e( 'Send your dates and we will personally confirm the practical details.', 'rentacar-venezia-v2' ); ?></p><a class="button button--secondary" href="<?php echo esc_url( rentacar_venezia_v2_fleet_url_with_trip( array( 'pickup_location' => $location['value'] ?? '' ) ) ); ?>"><?php esc_html_e( 'Explore the fleet', 'rentacar-venezia-v2' ); ?></a></section>
</article></main><?php endwhile; get_template_part( 'template-parts/enquiry/reservation-modal' ); get_footer();
