#!/usr/bin/env bash
set -Eeuo pipefail
local_wp_host() { local host=${LOCAL_WP_URL#*://}; host=${host%%/*}; host=${host%%:*}; [ -n "$host" ] || die 3 'LOCAL_WP_URL must include a hostname so LocalWP WP-CLI can bootstrap safely'; printf '%s\n' "$host"; }
wp_local() { HTTP_HOST="$(local_wp_host)" "$LOCAL_WP_COMMAND" --path="$LOCAL_WP_ROOT" "$@"; }
local_wp_check() { wp_local core is-installed >/dev/null 2>&1 || die 3 'LocalWP WP-CLI cannot access the site. Run from Local Site Shell or set LOCAL_WP_COMMAND to a working wrapper.'; }
local_php_bin() { local candidate; if [ -n "$LOCAL_PHP_BIN" ] && [ -x "$LOCAL_PHP_BIN" ]; then printf '%s\n' "$LOCAL_PHP_BIN"; return; fi; if command_exists php; then command -v php; return; fi; candidate=$(wp_local eval 'echo PHP_BINARY;' 2>/dev/null) || die 3 'PHP is unavailable. Set LOCAL_PHP_BIN or configure LOCAL_WP_COMMAND to a LocalWP WP-CLI wrapper that can report PHP_BINARY.'; [ -x "$candidate" ] || die 3 'LocalWP WP-CLI did not report an executable PHP_BINARY; set LOCAL_PHP_BIN to a PHP executable.'; printf '%s\n' "$candidate"; }
local_mysql_socket() { wp_local eval 'global $wpdb; echo $wpdb->get_var("SELECT @@socket");'; }
export_local_database() { local output=$1 socket; socket=$(local_mysql_socket) || die 3 'cannot determine the LocalWP MySQL socket through WordPress'; if [ -n "$socket" ]; then wp_local db export "$output" --add-drop-table "--socket=$socket"; else wp_local db export "$output" --add-drop-table; fi; }
local_code_preflight() { local php_bin; PHASE=local-preflight; require_clean_tree; [ -d "$PROJECT_ROOT/theme/rentacar-venezia-v2" ] && [ -f "$PROJECT_ROOT/plugin/rentacar-core/rentacar-core.php" ] || die 3 'owned theme or plugin missing'; local_wp_check; php_bin=$(local_php_bin); if [ -f "$PROJECT_ROOT/package-lock.json" ]; then (cd "$PROJECT_ROOT" && npm ci); elif [ -f "$PROJECT_ROOT/pnpm-lock.yaml" ] && command_exists pnpm; then (cd "$PROJECT_ROOT" && pnpm install --frozen-lockfile); else die 3 'a package-lock.json/npm ci or pnpm-lock.yaml/pnpm is required for repeatable dependency installation'; fi; (cd "$PROJECT_ROOT" && npm run check && npm run build && npm run check:assets && PHP_BIN="$php_bin" ./scripts/php-lint.sh && git diff --check) || die 3 'local build checks failed'; [ -f "$PROJECT_ROOT/theme/rentacar-venezia-v2/assets/dist/manifest.json" ] || die 3 'compiled assets missing'; if [ "$SKIP_LOCAL_TESTS" -ne 1 ] && [ "$RUN_BROWSER_TESTS" -eq 1 ] && [ "$SKIP_BROWSER_TESTS" -ne 1 ]; then (cd "$PROJECT_ROOT" && npm run test:browser) || die 3 'local browser tests failed'; fi; }
local_cutover_preflight() { local_code_preflight; export_local_database "$DEPLOY_RUNTIME/local-preflight.sql"; rm -f "$DEPLOY_RUNTIME/local-preflight.sql"; }
local_media_preflight() { [ -d "$LOCAL_WP_ROOT/wp-content/uploads" ] || die 3 'LocalWP uploads directory missing'; }
record_local_metadata() { LOCAL_PREFIX=$(wp_local db prefix); LOCAL_HOME=$(wp_local option get home); LOCAL_DB=$(wp_local eval 'global $wpdb; echo $wpdb->get_var("SELECT DATABASE()");'); }
