#!/usr/bin/env bash
set -Eeuo pipefail
ssh_args() { SSH_CONTROL_DIR='/tmp/rentacar-venezia-ssh'; mkdir -p "$SSH_CONTROL_DIR"; chmod 700 "$SSH_CONTROL_DIR"; SSH_CONTROL_PATH="$SSH_CONTROL_DIR/%C"; SSH_CONNECTION_ARGS=(-p "$PRODUCTION_SSH_PORT" -o BatchMode=no -o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=600 -o "ControlPath=$SSH_CONTROL_PATH"); [ -n "$PRODUCTION_SSH_IDENTITY_FILE" ] && SSH_CONNECTION_ARGS=("${SSH_CONNECTION_ARGS[@]}" -i "$PRODUCTION_SSH_IDENTITY_FILE"); SSH_ARGS=("${SSH_CONNECTION_ARGS[@]}" "$PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST"); }
rsync_ssh_command() { ssh_args; local command="ssh -p $(shell_quote "$PRODUCTION_SSH_PORT") -o BatchMode=no -o StrictHostKeyChecking=accept-new -o ControlMaster=auto -o ControlPersist=600 -o ControlPath=$(shell_quote "$SSH_CONTROL_PATH")"; [ -n "$PRODUCTION_SSH_IDENTITY_FILE" ] && command="$command -i $(shell_quote "$PRODUCTION_SSH_IDENTITY_FILE")"; printf '%s\n' "$command"; }
remote_exec() { ssh_args; if [ "${VERBOSE:-0}" -eq 1 ]; then info "remote command: $1"; fi; ssh "${SSH_ARGS[@]}" "bash -lc $(shell_quote "$1")"; }
wp_remote() { local command arg; command="cd $(shell_quote "$PRODUCTION_ROOT") && $(shell_quote "$REMOTE_WP_COMMAND")"; for arg in "$@"; do command="$command $(shell_quote "$arg")"; done; remote_exec "$command"; }
remote_value() { wp_remote "$@" | tail -n 1 | tr -d '\r'; }
discover_remote_roots() { local candidates; candidates=$(remote_exec 'for d in "$HOME"/domains/*/public_html; do test -f "$d/wp-config.php" && printf "%s\n" "$d"; done' 2>/dev/null) || { warn 'could not discover Hostinger WordPress roots; enter the exact absolute path'; return; }; if [ -n "$candidates" ]; then info 'Hostinger WordPress root candidates:'; printf '%s\n' "$candidates" >&2; else warn 'no wp-config.php candidates found under ~/domains/*/public_html'; fi; }
verify_remote_target() { PHASE=remote-safety; local wp_info; ssh_args; ssh "${SSH_ARGS[@]}" true >/dev/null || die 4 'cannot connect to configured SSH target'; remote_exec "test -f $(shell_quote "$PRODUCTION_ROOT/wp-config.php")" || die 4 'production wp-config.php is absent'; remote_exec "test -d $(shell_quote "$PRODUCTION_ROOT/wp-includes")" || die 4 'production root is not a WordPress installation'; if ! wp_info=$(wp_remote --info 2>&1); then case "$wp_info" in *proc_open*|*proc_close*) die 4 'remote WP-CLI is blocked because Hostinger disables proc_open/proc_close. In hPanel: Websites → Dashboard → PHP Configuration → PHP options → disableFunctions, remove proc_open and proc_close, save, then rerun setup.';; *) die 4 'remote WP-CLI is unavailable; configure REMOTE_WP_COMMAND to a working command';; esac; fi; REMOTE_HOME=$(normalize_url "$(remote_value option get home)") || die 4 'remote home URL malformed'; REMOTE_SITEURL=$(normalize_url "$(remote_value option get siteurl)") || die 4 'remote siteurl malformed'; [ "$REMOTE_HOME" = "$PRODUCTION_URL" ] || die 4 "remote home does not match production URL"; [ "$REMOTE_SITEURL" = "$PRODUCTION_URL" ] || die 4 "remote siteurl does not match production URL"; REMOTE_DB=$(wp_remote eval 'global $wpdb; echo $wpdb->get_var("SELECT DATABASE()");' | tail -n1); [ "$REMOTE_DB" = "$PRODUCTION_EXPECTED_DB_NAME" ] || die 4 "remote database '$REMOTE_DB' does not match PRODUCTION_EXPECTED_DB_NAME '$PRODUCTION_EXPECTED_DB_NAME'"; REMOTE_PREFIX=$(remote_value db prefix); [ -n "$REMOTE_PREFIX" ] || die 4 'remote table prefix is unavailable'; remote_exec "test -w $(shell_quote "$PRODUCTION_ROOT/wp-content/themes") && test -w $(shell_quote "$PRODUCTION_ROOT/wp-content/plugins") && test -w $(shell_quote "$PRODUCTION_ROOT/wp-content/uploads") && mkdir -p $(shell_quote "$REMOTE_BACKUP_ROOT") && test -w $(shell_quote "$REMOTE_BACKUP_ROOT")" || die 4 'production paths or backup root are not writable'; remote_exec 'command -v tar >/dev/null && command -v gzip >/dev/null' || die 4 'remote tar/gzip unavailable'; ok "verified production target $PRODUCTION_URL"; }
