<?php
defined( 'ABSPATH' ) || exit;
get_header();
$vehicle = class_exists( 'Rentacar_Core_Vehicle_Repository' ) ? ( new Rentacar_Core_Vehicle_Repository() )->find( get_queried_object_id() ) : null;
if ( ! $vehicle ) { get_template_part( 'index' ); get_footer(); return; }
$image_ids = $vehicle->get( 'vehicle_gallery' )->all_image_ids();
$image = $vehicle->get( 'featured_image_id' ) ? wp_get_attachment_image_url( $vehicle->get( 'featured_image_id' ), 'medium_large' ) : '';
$specifications = array_filter( array( $vehicle->get( 'transmission' ), $vehicle->get( 'passengers' ) ? sprintf( __( '%s passengers', 'rentacar-venezia-v2' ), $vehicle->get( 'passengers' ) ) : '', $vehicle->get( 'doors' ) ? sprintf( __( '%s doors', 'rentacar-venezia-v2' ), $vehicle->get( 'doors' ) ) : '', $vehicle->get( 'air_conditioning' ) ? __( 'Air conditioning', 'rentacar-venezia-v2' ) : '' ) );
$price_labels = array();
foreach ( $vehicle->get( 'pricing_bands' )->all() as $band ) { if ( $band->from_days >= 1 && null !== $band->daily_price && $band->daily_price > 0 ) { $price_labels[] = null === $band->to_days ? sprintf( __( '%1$s+ days €%2$s/day', 'rentacar-venezia-v2' ), $band->from_days, number_format_i18n( $band->daily_price, 0 ) ) : sprintf( __( '%1$s–%2$s days €%3$s/day', 'rentacar-venezia-v2' ), $band->from_days, $band->to_days, number_format_i18n( $band->daily_price, 0 ) ); } }
?>
<main id="main-content" class="site-main vehicle-page"><div class="rc-container">
<nav class="breadcrumbs" aria-label="<?php esc_attr_e( 'Breadcrumbs', 'rentacar-venezia-v2' ); ?>"><a href="<?php echo esc_url( home_url( '/' ) ); ?>"><?php esc_html_e( 'Home', 'rentacar-venezia-v2' ); ?></a><span>/</span><a href="<?php echo esc_url( rentacar_venezia_v2_fleet_url() ); ?>"><?php esc_html_e( 'Fleet', 'rentacar-venezia-v2' ); ?></a><span>/</span><span aria-current="page"><?php echo esc_html( $vehicle->get( 'title' ) ); ?></span></nav>
<div class="vehicle-page__grid"><section class="vehicle-page__content"><div class="vehicle-gallery" aria-label="<?php esc_attr_e( 'Vehicle gallery', 'rentacar-venezia-v2' ); ?>">
<?php if ( $image_ids ) : foreach ( $image_ids as $index => $image_id ) : ?><figure class="vehicle-gallery__image<?php echo 0 === $index ? ' vehicle-gallery__image--primary' : ''; ?>"><?php echo wp_kses_post( wp_get_attachment_image( $image_id, 0 === $index ? 'large' : 'medium_large', false, array( 'loading' => 0 === $index ? 'eager' : 'lazy' ) ) ); ?></figure><?php endforeach; else : ?><div class="vehicle-gallery__image vehicle-gallery__image--primary vehicle-card__image-placeholder"><?php esc_html_e( 'Vehicle image coming soon', 'rentacar-venezia-v2' ); ?></div><?php endif; ?></div>
<header class="vehicle-page__heading"><p class="eyebrow"><?php esc_html_e( 'Our fleet', 'rentacar-venezia-v2' ); ?></p><h1><?php echo esc_html( $vehicle->get( 'title' ) ); ?></h1><ul class="specification-list"><?php foreach ( $specifications as $specification ) : ?><li><?php echo esc_html( $specification ); ?></li><?php endforeach; ?></ul></header>
<section class="vehicle-copy"><h2><?php esc_html_e( 'Indicative price bands', 'rentacar-venezia-v2' ); ?></h2><dl class="vehicle-card__prices vehicle-page__prices"><?php foreach ( $vehicle->get( 'pricing_bands' )->all() as $band ) : if ( $band->from_days < 1 || null === $band->daily_price || $band->daily_price <= 0 || ( null !== $band->to_days && $band->to_days < $band->from_days ) ) { continue; } ?><div><dt><?php echo esc_html( null === $band->to_days ? sprintf( __( '%s+ days', 'rentacar-venezia-v2' ), $band->from_days ) : sprintf( __( '%1$s–%2$s days', 'rentacar-venezia-v2' ), $band->from_days, $band->to_days ) ); ?></dt><dd><?php echo esc_html( sprintf( __( '€%s/day', 'rentacar-venezia-v2' ), number_format_i18n( $band->daily_price, 0 ) ) ); ?></dd></div><?php endforeach; ?></dl><p><?php esc_html_e( 'Indicative prices only. Availability and final price are confirmed by our team.', 'rentacar-venezia-v2' ); ?></p></section></section>
<aside class="request-card"><p class="eyebrow"><?php esc_html_e( 'Reservation request', 'rentacar-venezia-v2' ); ?></p><h2><?php esc_html_e( 'Choose this vehicle', 'rentacar-venezia-v2' ); ?></h2><p><?php esc_html_e( 'Send one short request and our team will check availability personally.', 'rentacar-venezia-v2' ); ?></p><button class="button reservation-trigger" type="button" data-reservation-trigger data-vehicle-id="<?php echo esc_attr( $vehicle->get( 'id' ) ); ?>" data-vehicle-title="<?php echo esc_attr( $vehicle->get( 'title' ) ); ?>" data-vehicle-image="<?php echo esc_url( $image ); ?>" data-vehicle-specifications="<?php echo esc_attr( implode( ' · ', $specifications ) ); ?>" data-vehicle-price-bands="<?php echo esc_attr( implode( ' · ', $price_labels ) ); ?>" aria-label="<?php echo esc_attr( sprintf( __( 'Reservation for %s', 'rentacar-venezia-v2' ), $vehicle->get( 'title' ) ) ); ?>"><?php esc_html_e( 'Reservation', 'rentacar-venezia-v2' ); ?></button></aside></div>
</div></main><?php get_template_part( 'template-parts/enquiry/reservation-modal' ); get_footer();
