<?php
defined( 'ABSPATH' ) || exit;

function rentacar_venezia_v2_multilingual_provider() { return function_exists( 'pll_current_language' ) ? 'polylang' : ( has_filter( 'wpml_current_language' ) ? 'wpml' : 'none' ); }
function rentacar_venezia_v2_current_language() { $provider = rentacar_venezia_v2_multilingual_provider(); return 'polylang' === $provider ? pll_current_language( 'slug' ) : ( 'wpml' === $provider ? (string) apply_filters( 'wpml_current_language', '' ) : substr( determine_locale(), 0, 2 ) ); }
function rentacar_venezia_v2_default_language() { $provider = rentacar_venezia_v2_multilingual_provider(); return 'polylang' === $provider ? pll_default_language( 'slug' ) : ( 'wpml' === $provider ? (string) apply_filters( 'wpml_default_language', '' ) : rentacar_venezia_v2_current_language() ); }
function rentacar_venezia_v2_post_language( $post_id ) { return 'polylang' === rentacar_venezia_v2_multilingual_provider() ? pll_get_post_language( $post_id, 'slug' ) : ( has_filter( 'wpml_element_language_code' ) ? (string) apply_filters( 'wpml_element_language_code', null, array( 'element_id' => (int) $post_id, 'element_type' => 'post_' . get_post_type( $post_id ) ) ) : '' ); }
function rentacar_venezia_v2_translated_post_id( $post_id, $language = null ) { $language = $language ?: rentacar_venezia_v2_current_language(); return 'polylang' === rentacar_venezia_v2_multilingual_provider() ? (int) pll_get_post( $post_id, $language ) : ( has_filter( 'wpml_object_id' ) ? (int) apply_filters( 'wpml_object_id', $post_id, get_post_type( $post_id ), false, $language ) : (int) $post_id ); }
function rentacar_venezia_v2_translations( $post_id ) { return 'polylang' === rentacar_venezia_v2_multilingual_provider() ? (array) pll_get_post_translations( $post_id ) : array(); }
function rentacar_venezia_v2_translated_permalink( $post_id, $language = null ) { $translated = rentacar_venezia_v2_translated_post_id( $post_id, $language ); return $translated ? get_permalink( $translated ) : ''; }
function rentacar_venezia_v2_languages() { if ( 'polylang' === rentacar_venezia_v2_multilingual_provider() ) return pll_the_languages( array( 'raw' => 1, 'hide_if_no_translation' => 0 ) ); return (array) apply_filters( 'wpml_active_languages', array(), array( 'skip_missing' => 0, 'orderby' => 'code' ) ); }
